# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 395)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.die_roll_widg = QtWidgets.QFrame(self.centralWidget)
        self.die_roll_widg.setGeometry(QtCore.QRect(480, 90, 165, 101))
        self.die_roll_widg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.die_roll_widg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.die_roll_widg.setObjectName("die_roll_widg")
        self.gridLayout = QtWidgets.QGridLayout(self.die_roll_widg)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.die_roll_widg)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.die_roll_widg)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.die_roll_widg)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 2)
        self.spinBox = QtWidgets.QSpinBox(self.die_roll_widg)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 2, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.die_roll_widg)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout.addWidget(self.spinBox_2, 2, 2, 1, 1)
        self.property_widget = QtWidgets.QFrame(self.centralWidget)
        self.property_widget.setGeometry(QtCore.QRect(330, 50, 151, 70))
        self.property_widget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.property_widget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.property_widget.setObjectName("property_widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.property_widget)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_4 = QtWidgets.QLabel(self.property_widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.yes_no_Combobox_2 = QtWidgets.QComboBox(self.property_widget)
        self.yes_no_Combobox_2.setObjectName("yes_no_Combobox_2")
        self.yes_no_Combobox_2.addItem("")
        self.yes_no_Combobox_2.addItem("")
        self.gridLayout_6.addWidget(self.yes_no_Combobox_2, 1, 0, 1, 1)
        self.mortgage_widg = QtWidgets.QFrame(self.centralWidget)
        self.mortgage_widg.setGeometry(QtCore.QRect(330, 190, 321, 102))
        self.mortgage_widg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mortgage_widg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mortgage_widg.setObjectName("mortgage_widg")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mortgage_widg)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.mortgage_widg)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.mortgage_widg)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.mortgage_widg)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.mortgage_widg)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.mortgage_widg)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 2)
        self.trade_widg = QtWidgets.QFrame(self.centralWidget)
        self.trade_widg.setGeometry(QtCore.QRect(0, 130, 331, 161))
        self.trade_widg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trade_widg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trade_widg.setObjectName("trade_widg")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.trade_widg)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.trade_widg)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.trade_widg)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.trade_widg)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_3.addWidget(self.comboBox_3, 1, 1, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.trade_widg)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_3.addWidget(self.comboBox_4, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.trade_widg)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 2, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.trade_widg)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 2, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.trade_widg)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 2, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.trade_widg)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 3, 0, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.trade_widg)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_3.addWidget(self.spinBox_3, 3, 1, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.trade_widg)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_3.addWidget(self.spinBox_4, 3, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.trade_widg)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 4, 0, 1, 1)
        self.yes_no_Combobox_3 = QtWidgets.QComboBox(self.trade_widg)
        self.yes_no_Combobox_3.setObjectName("yes_no_Combobox_3")
        self.yes_no_Combobox_3.addItem("")
        self.yes_no_Combobox_3.addItem("")
        self.gridLayout_3.addWidget(self.yes_no_Combobox_3, 4, 1, 1, 1)
        self.yes_no_Combobox_4 = QtWidgets.QComboBox(self.trade_widg)
        self.yes_no_Combobox_4.setObjectName("yes_no_Combobox_4")
        self.yes_no_Combobox_4.addItem("")
        self.yes_no_Combobox_4.addItem("")
        self.gridLayout_3.addWidget(self.yes_no_Combobox_4, 4, 2, 1, 1)
        self.bankruptcy_widg = QtWidgets.QFrame(self.centralWidget)
        self.bankruptcy_widg.setGeometry(QtCore.QRect(330, 120, 151, 70))
        self.bankruptcy_widg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bankruptcy_widg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bankruptcy_widg.setObjectName("bankruptcy_widg")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.bankruptcy_widg)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_8 = QtWidgets.QLabel(self.bankruptcy_widg)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 1)
        self.yes_no_Combobox = QtWidgets.QComboBox(self.bankruptcy_widg)
        self.yes_no_Combobox.setObjectName("yes_no_Combobox")
        self.yes_no_Combobox.addItem("")
        self.yes_no_Combobox.addItem("")
        self.gridLayout_5.addWidget(self.yes_no_Combobox, 1, 0, 1, 1)
        self.label_8.raise_()
        self.yes_no_Combobox.raise_()
        self.trade_widg.raise_()
        self.real_estate_widg = QtWidgets.QFrame(self.centralWidget)
        self.real_estate_widg.setGeometry(QtCore.QRect(0, 0, 329, 130))
        self.real_estate_widg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.real_estate_widg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.real_estate_widg.setObjectName("real_estate_widg")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.real_estate_widg)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_15 = QtWidgets.QLabel(self.real_estate_widg)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.real_estate_widg)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 3, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.real_estate_widg)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_4.addWidget(self.lineEdit_8, 3, 3, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.real_estate_widg)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_4.addWidget(self.lineEdit_7, 2, 3, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.real_estate_widg)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_4.addWidget(self.lineEdit_6, 3, 1, 1, 2)
        self.label_18 = QtWidgets.QLabel(self.real_estate_widg)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 1, 2, 1, 2)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.real_estate_widg)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_4.addWidget(self.lineEdit_5, 2, 1, 1, 2)
        self.label_19 = QtWidgets.QLabel(self.real_estate_widg)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.real_estate_widg)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 4)
        self.submit_button = QtWidgets.QDialogButtonBox(self.centralWidget)
        self.submit_button.setGeometry(QtCore.QRect(490, 300, 164, 32))
        self.submit_button.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.submit_button.setObjectName("submit_button")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 660, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuMonopoly_AI_GUI = QtWidgets.QMenu(self.menuBar)
        self.menuMonopoly_AI_GUI.setObjectName("menuMonopoly_AI_GUI")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuMonopoly_AI_GUI.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Roll"))
        self.label_2.setText(_translate("MainWindow", "Die 1"))
        self.label_3.setText(_translate("MainWindow", "Die 2"))
        self.label_4.setText(_translate("MainWindow", "Buy Property"))
        self.yes_no_Combobox_2.setItemText(0, _translate("MainWindow", "no"))
        self.yes_no_Combobox_2.setItemText(1, _translate("MainWindow", "yes"))
        self.label_10.setText(_translate("MainWindow", "Mortgage"))
        self.label_11.setText(_translate("MainWindow", "Unmortgage"))
        self.label_6.setText(_translate("MainWindow", "Mortgage"))
        self.label_7.setText(_translate("MainWindow", "Trade"))
        self.label_5.setText(_translate("MainWindow", "Player"))
        self.label_12.setText(_translate("MainWindow", "Properties"))
        self.label_13.setText(_translate("MainWindow", "Money"))
        self.label_14.setText(_translate("MainWindow", "Out Jail Free"))
        self.yes_no_Combobox_3.setItemText(0, _translate("MainWindow", "no"))
        self.yes_no_Combobox_3.setItemText(1, _translate("MainWindow", "yes"))
        self.yes_no_Combobox_4.setItemText(0, _translate("MainWindow", "no"))
        self.yes_no_Combobox_4.setItemText(1, _translate("MainWindow", "yes"))
        self.label_8.setText(_translate("MainWindow", "Declare Bankruptcy"))
        self.yes_no_Combobox.setItemText(0, _translate("MainWindow", "no"))
        self.yes_no_Combobox.setItemText(1, _translate("MainWindow", "yes"))
        self.label_15.setText(_translate("MainWindow", "Buy"))
        self.label_16.setText(_translate("MainWindow", "Sell"))
        self.label_18.setText(_translate("MainWindow", "                   Num Pieces"))
        self.label_19.setText(_translate("MainWindow", "        Properties"))
        self.label_9.setText(_translate("MainWindow", "Build Real Estate "))
        self.menuMonopoly_AI_GUI.setTitle(_translate("MainWindow", "Monopoly AI GUI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

